#Author-Bob M
#Description-First attempt at generating splines from boat hull offset table lines

import adsk.core, adsk.fusion, adsk.cam, traceback
#import pandas as pd


def add_spline(point_list, sketch):
    '''Adds a spline to the current drawing given an set of points in 3-space'''

    # Create an object collection for the points.
    points = adsk.core.ObjectCollection.create()

    for p in point_list:
        points.add(adsk.core.Point3D.create(*p))

    # Create the spline.
    sketch.sketchCurves.sketchFittedSplines.add(points)

    # Do again for other side (TODO: Mirror?)
    points1 = adsk.core.ObjectCollection.create()
    for p in point_list:
        points1.add(adsk.core.Point3D.create(-p[0],p[1],p[2]))

    sketch.sketchCurves.sketchFittedSplines.add(points1)

    
def run(context):
    ui = None
    try:
        app = adsk.core.Application.get()
        ui  = app.userInterface
        #ui.messageBox('Hello script')

        doc = app.documents.add(adsk.core.DocumentTypes.FusionDesignDocumentType)
        design = app.activeProduct

        # Get the root component of the active design.
        rootComp = design.rootComponent

        # Create a new sketch on the xy plane.
        sketch = rootComp.sketches.add(rootComp.xYConstructionPlane)

        # Pull in points generated by 'python linetab2solid.py Cartopper.csv'
        bottom=[[6.0, 21.0, 0.0], [7.625, 23.25, 12.0], [9.0, 25.25, 24.0], [10.25, 26.75, 36.0], [10.875, 27.625, 48.0], [11.25, 28.0, 60.0], [10.625, 27.875, 72.0], [9.25, 27.25, 84.0], [7.0, 26.125, 96.0], [4.125, 24.625, 108.0], [0.75, 21.5, 120.0], [0.25, 16.25, 129.0], [0.125, 3.0, 138.0]]
        chine=[[13.375, 16.125, 0.0], [15.75, 17.625, 12.0], [18.0, 19.0, 24.0], [19.875, 20.0, 36.0], [21.0, 20.75, 48.0], [21.5, 21.0, 60.0], [21.0, 20.625, 72.0], [19.375, 19.75, 84.0], [16.75, 18.25, 96.0], [12.875, 15.875, 108.0], [8.0, 12.875, 120.0], [3.625, 10.25, 129.0], [0.5, 2.0, 138.0]]
        gunwale=[[15.875, 7.75, 0.0], [18.25, 9.5, 12.0], [20.375, 10.875, 24.0], [22.25, 11.75, 36.0], [23.625, 12.125, 48.0], [24.125, 12.125, 60.0], [23.625, 11.5, 72.0], [22.125, 10.5, 84.0], [19.375, 9.125, 96.0], [15.5, 7.375, 108.0], [10.25, 5.125, 120.0], [5.625, 3.25, 129.0], [0.5, 1.0, 138.0]]

        # Create a spline (two of them actually) for each line
        add_spline(bottom, sketch)
        add_spline(chine, sketch)
        add_spline(gunwale, sketch)

    except:
        if ui:
            ui.messageBox('Failed:\n{}'.format(traceback.format_exc()))